name: On PR Push - Checks

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  on-pr-push-checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Tests
        run: cargo check
      - name: Formatting Tests
        run: cargo fmt --check
      - name: Lint Tests
        run: cargo clippy --all -- -D warnings
      - name: Build Tests - Contract
        run: |

          # trigger toolchain download
          rustc -vV
          rustup default nightly-2023-08-08
        
          # get platform for precompiled
          PLATFORM="$(echo $(echo $(uname) | tr '[:upper:]' '[:lower:]')/$(if [[ $(uname -m) = x86_64 ]]; then echo amd64; else echo arm64; fi))"
          PRECOMPILED_CC="utilities/precompiled/${PLATFORM}/cargo-contract"

          # check
          ${PRECOMPILED_CC} contract check --manifest-path contract/Cargo.toml
